[package]
name = "wise_units-ffi"
version = "0.15.0"
authors = ["Nicholas Smillie <nicholas@agrian.com>"]
edition = "2018"
publish = ["agrian-registry"]

[dependencies]
ffi_common = { version = "0.1", registry = "agrian-registry" }
wise_units = { path = "../api" }

[build-dependencies]
cbindgen = "0.13.1"

[dev-dependencies]
approx = "0.3"

[lib]
crate-type = ["staticlib", "rlib", "cdylib"]
