[package]
name = "wise_units-ffi"
version = "0.2.0"
authors = ["Nicholas Smillie <nicholas@agrian.com>"]
edition = "2018"

[dependencies]
wise_units = { path = "../api" }

[dependencies.ffi_common]
git = "ssh://bitbucket.org/agrian/ffi_common.git"
rev = "7ddeec9"

[build-dependencies]
cbindgen = "0.13.1"

[dev-dependencies]
approx = "0.3"

[lib]
crate-type = ["staticlib", "rlib", "cdylib"]
