[package]
name = "wise_units-ffi"
version = "0.1.0"
authors = ["Nicholas Smillie <nicholas@agrian.com>"]
edition = "2018"

[dependencies]
wise_units = { path = "../api" }

[build-dependencies]
cbindgen = "0.9.1"

[dev-dependencies]
approx = "0.3"

[lib]
crate-type = ["staticlib", "rlib"]
