[package]
name = "wise_units"
version = "0.1.0"
authors = ["Steve Loveless <steve@agrian.com>"]

[dependencies]
failure = "0.1"
failure_derive = "0.1"
pest = "^1.0"
pest_derive = "^1.0"

[dev-dependencies]
criterion = "0.1.2"
pretty_assertions = "*"

[[bench]]
name = "measurements_benchmarks"
harness = false

[[bench]]
name = "unit_benchmarks"
harness = false
