[workspace]
members = [
  "api",
  "atom_generator",
  "definition_fetcher",
  "ffi",
]

[patch."agrian-registry".ffi_common]
# path = "../ffi_common/ffi_common"
git = "ssh://git@bitbucket.org/agrian/ffi_common.git"
branch = "develop"

[patch."agrian-registry".ffi_derive]
# path = "../ffi_common/ffi_derive"
git = "ssh://git@bitbucket.org/agrian/ffi_common.git"
branch = "develop"
