[package]
name = "wu"
version = "0.1.0"
authors = ["Steve Loveless <steve@agrian.com>"]
build = "build.rs"

[build-dependencies]
lalrpop = "0.13.0"

[dependencies]
lalrpop-util = "0.13.0"

[dev-dependencies]
pretty_assertions = "*"
