[package]
name = "wise_units"
version = "0.1.0"
authors = ["Steve Loveless <steve@agrian.com>"]

[dependencies]
pest = "1.0.0-beta"
pest_derive = "1.0.0-beta"

[dev-dependencies]
pretty_assertions = "*"
