[package]
name = "wise_units-definition_fetcher"
version = "0.2.0"
authors = ["Steve Loveless <steve@agrian.com>"]
edition = "2018"

[dependencies]
reqwest = "0.10"
serde-transcode = "1.0"
serde-xml-rs = "0.4"
simple_logger = "1.6"
toml = "0.5"
