[package]
name = "wise_units"
version = "0.15.0"
description = "Measure things using UCUM units"
documentation = "https://teamcity-build.agriandev.com/repository/download/Crates_WiseUnits_Test/369131:id/docs/wise_units/index.html"
repository = "https://github.com/agrian-inc/wise_units"
license = "MIT"
authors = ["Steve Loveless <steve@agrian.com>"]
edition = "2018"
publish = ["agrian-registry"]

[dependencies]
approx = "0.3"
pest = "^1.0"
pest_derive = "^1.0"
serde = { version = "1.0", optional = true, features = ["derive"] }
thiserror = "1.0"
paste = { version = "1.0", optional = true }
ffi_common = { version = "0.1", registry = "agrian-registry", optional = true }
ffi_derive = { version = "0.1", registry = "agrian-registry", optional = true }

[dev-dependencies]
bincode = "1.1"
criterion = "0.3"
lazy_static = "1.4"
rmp-serde = "0.13"
serde_json = "1.0"

[features]
# Enables the C foreign function interface. Some types may become repr(C) under this flag, and an
# additional ffi module will be generated for each supported resource type.
cffi = ["ffi_derive", "paste", "ffi_common"]

[[bench]]
name = "measurements_benchmarks"
harness = false

[[bench]]
name = "unit_benchmarks"
harness = false
