[package]
name = "wise_units"
version = "0.11.0"
authors = ["Steve Loveless <steve@agrian.com>"]
edition = "2018"

[dependencies]
approx = "0.3"
failure = "0.1"
failure_derive = "0.1"
pest = "^1.0"
pest_derive = "^1.0"
serde = { version = "1.0", optional = true, features = ["derive"] }

[dev-dependencies]
bincode = "1.1"
criterion = "0.2"
lazy_static = "1.0"
rmp-serde = "0.13"
serde_json = "1.0"

[build-dependencies]
wise_units-atom_generator = { path = "../atom_generator" }

[[bench]]
name = "measurements_benchmarks"
harness = false

[[bench]]
name = "unit_benchmarks"
harness = false
