[package]
name = "wise_units"
version = "0.1.0"
authors = ["Steve Loveless <steve@agrian.com>"]

[dependencies]
serde = { version = "1.0", optional = true, default-features = false }
serde_derive = { version = "1.0", optional = true, default-features = false }
stdweb = { version = "0.4", optional = true, default-features = false }
wise_units-parsing = { path = "../parsing" }

[build-dependencies]
serde = "1.0"
serde_derive = "1.0"
toml = "0.4"

[dev-dependencies]
approx = "0.1"
criterion = "0.1.2"
pretty_assertions = "*"
serde_json = { version = "1.0", default-features = false }

[features]
with_serde = ["serde", "serde_derive"]
with_stdweb = ["stdweb", "with_serde"]

[[bench]]
name = "measurements_benchmarks"
harness = false

[[bench]]
name = "unit_benchmarks"
harness = false
