name: Continuous Integration

on:
  push:
  pull_request:
    branches: [ develop ]

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRIES_AGRIAN_REGISTRY_INDEX: ${{ secrets.AGRIAN_CRATES_REGISTRY }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup SSH
        uses: webfactory/ssh-agent@ee29fafb6aa450493bac9136b346e51ea60a8b5e
        with:
          ssh-private-key: |
            ${{ secrets.MAC_OS_BUILD_AGENT_PRIVATE_KEY }}
            ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}
            ${{ runner.os }}-cargo
      - name: cargo test all
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace
